#If BLACKLIST, the list below will be treated as a blacklist what not to touch.
#If WHITELIST, the will be treated as a whitelist what biomes should only be touched
#Allowed Values: WHITELIST, BLACKLIST
listMode = "BLACKLIST"
#The blacklist or whitelist, depending on listMode
biomeList = ["minecraft:basalt_deltas", "regions_unexplored:blackstone_basin", "minecraft:crimson_forest", "regions_unexplored:glistering_meadow", "regions_unexplored:infernal_holt", "regions_unexplored:mycotoxic_undergrowth", "minecraft:nether_wastes", "regions_unexplored:redstone_abyss", "minecraft:soul_sand_valley", "minecraft:warped_forest", "minecraft:end_barrens", "minecraft:end_highlands", "minecraft:end_midlands", "minecraft:small_end_islands", "minecraft:the_end", "creatingspace:mars_plains", "creatingspace:moon_cave", "creatingspace:moon_plains", "creatingspace:space", "creatingspace:venus", "creatingspace:venus_hellground"]
#The downfall value each biome should get. If -1, EternalWinter will keep the original downfall of the biome, otherwise it takes a value between 0 and 1
#Range: -1.0 ~ 1.0
downfall = -1.0
#Temperature for each affected biome. In range [-0.5, 2]
#Range: -0.5 ~ 2.0
temperature = -0.5

