
#General mod settings
[general]
	#-
	Storm_NoSnowstorms = false
	#-
	Snowstorm_UseGlobalServerRate = true
	#-
	#Range: > -2147483648
	Snowstorm_OddsTo1 = 5
	#Time between snowstorms for either each player or entire server depending on if global rate is on, default: 3 client days
	#Range: > -2147483648
	Snowstorm_TimeBetweenInTicks = 1200
	#Amount of game ticks between snow buildup iterations, keep it high to prevent client side chunk tick spam that destroys FPS
	#Range: > -2147483648
	Snowstorm_Snow_Buildup_TickRate = 40
	#Base amount of loops done per iteration, scaled by the snowstorms intensity (value given here is the max possible), eg: at max storm intensity, every 40th tick, itll try to build up snow in 800 places around the storm
	#Range: > -2147483648
	Snowstorm_Snow_Buildup_LoopAmountBase = 800
	#Max height of snow allowed to buildup against something, higher = things get more buried over time
	#Range: > -2147483648
	Snowstorm_Snow_Block_Max_Height = 5
	#Allow layered snow blocks to buildup outside cold biomes where snowstorm is
	Snowstorm_Snow_Buildup_AllowOutsideColdBiomes = true
	#-
	#Range: > -2147483648
	Snowstorm_MaxAge_Base = 7200
	#-
	#Range: > -2147483648
	Snowstorm_MaxAge_Rnd = 24000
	#-
	#Range: > -2147483648
	Snowstorm_Radius_Base = 900
	#-
	#Range: > -2147483648
	Snowstorm_Radius_Rnd = 1500
	#-
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	Snowstorm_StormEdgeOffsetToSpawnAnother = 100.0
	#-
	Snowstorm_UseSereneSeasons = true
	#-
	#Range: > -2147483648
	Snowstorm_EarlySpring_OddsTo1 = 5
	#-
	#Range: > -2147483648
	Snowstorm_EarlySpring_TimeBetweenInTicks = 1200
	#-
	#Range: > -2147483648
	Snowstorm_MidSpring_OddsTo1 = 5
	#-
	#Range: > -2147483648
	Snowstorm_MidSpring_TimeBetweenInTicks = 1200
	#-
	#Range: > -2147483648
	Snowstorm_LateSpring_OddsTo1 = 7
	#-
	#Range: > -2147483648
	Snowstorm_LateSpring_TimeBetweenInTicks = 1200
	#-
	#Range: > -2147483648
	Snowstorm_EarlySummer_OddsTo1 = 10
	#-
	#Range: > -2147483648
	Snowstorm_EarlySummer_TimeBetweenInTicks = 1200
	#-
	#Range: > -2147483648
	Snowstorm_MidSummer_OddsTo1 = 12
	#-
	#Range: > -2147483648
	Snowstorm_MidSummer_TimeBetweenInTicks = 1200
	#-
	#Range: > -2147483648
	Snowstorm_LateSummer_OddsTo1 = 15
	#-
	#Range: > -2147483648
	Snowstorm_LateSummer_TimeBetweenInTicks = 1200
	#-
	#Range: > -2147483648
	Snowstorm_EarlyAutumn_OddsTo1 = 12
	#-
	#Range: > -2147483648
	Snowstorm_EarlyAutumn_TimeBetweenInTicks = 1200
	#-
	#Range: > -2147483648
	Snowstorm_MidAutumn_OddsTo1 = 8
	#-
	#Range: > -2147483648
	Snowstorm_MidAutumn_TimeBetweenInTicks = 1200
	#-
	#Range: > -2147483648
	Snowstorm_LateAutumn_OddsTo1 = 5
	#-
	#Range: > -2147483648
	Snowstorm_LateAutumn_TimeBetweenInTicks = 1200
	#-
	#Range: > -2147483648
	Snowstorm_EarlyWinter_OddsTo1 = 4
	#-
	#Range: > -2147483648
	Snowstorm_EarlyWinter_TimeBetweenInTicks = 1200
	#-
	#Range: > -2147483648
	Snowstorm_MidWinter_OddsTo1 = 150
	#-
	#Range: > -2147483648
	Snowstorm_MidWinter_TimeBetweenInTicks = 2400
	#-
	#Range: > -2147483648
	Snowstorm_LateWinter_OddsTo1 = 1
	#-
	#Range: > -2147483648
	Snowstorm_LateWinter_TimeBetweenInTicks = 199

