name: RestartServer

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  restart:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Send restart commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            SESSION="minecraft"

            tmux send-keys -t "$SESSION" C-u "/stop" Enter
            
            echo "Waiting for Minecraft to shut down..."
            
            while tmux has-session -t "$SESSION" 2>/dev/null; do
              sleep 1
            done
            
            echo "Server stopped. Restarting..."

            TIMEOUT=100

            # Start minecraft session
            tmux new-session -s "$SESSION" -d "bash -c 'cd /var/server; sh run.sh'"

            # Wait for potential session termination
            elapsed=0
            while [ $elapsed -lt $TIMEOUT ]; do
            if ! tmux has-session -t "$SESSION" 2>/dev/null; then
            echo "Server startup has failed"
            exit 1
            fi

            sleep 1
            elapsed=$(echo "$elapsed + 1" | bc)
            done

            echo "No exit occured in $elapsed s. Assume successful server start"
